=== vanallenlab/moalmanac-db/schemas/dereferenced/diseases.schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "https://moalmanac.org/schemas/dereferenced/diseases.schema.json",
  "title": "Disease",
  "description": "A cancer type concept with its primary coding and mappings embedded.",
  "type": "object",
  "properties": {
    "id": {
      "type": "string",
      "pattern": "^dis:(oncotree|ncit):.+$"
    },
    "conceptType": {
      "const": "Disease"
    },
    "name": {
      "type": "string"
    },
    "primaryCoding": {
      "$ref": "codings.schema.json"
    },
    "mappings": {
      "type": "array",
      "items": {
        "$ref": "mappings.schema.json#/$defs/ConceptMapping"
      }
    },
    "extensions": {
      "type": "array",
      "items": {
        "anyOf": [
          {
            "$ref": "extension.schema.json",
            "properties": {
              "name": {
                "const": "solid_tumor"
              },
              "value": {
                "type": "boolean"
              }
            }
          }
        ]
      },
      "allOf": [
        {
          "contains": {
            "$ref": "extension.schema.json",
            "properties": {
              "name": {
                "const": "solid_tumor"
              },
              "value": {
                "type": "boolean"
              }
            }
          }
        }
      ]
    }
  },
  "required": [
    "id",
    "conceptType",
    "name",
    "primaryCoding",
    "mappings",
    "extensions"
  ],
  "additionalProperties": false
}

=== vanallenlab/moalmanac-db/dereferenced/diseases/dis_ncit_C3704.json
{
  "id": "dis:ncit:C3704",
  "conceptType": "Disease",
  "name": "Dedifferentiated Liposarcoma",
  "mappings": [
    {
      "relation": "exactMatch",
      "coding": {
        "id": "coding:oncotree:DDLS",
        "code": "DDLS",
        "name": "Dedifferentiated Liposarcoma",
        "system": "https://oncotree.mskcc.org",
        "systemVersion": "oncotree_2025_10_03",
        "iris": [
          "https://oncotree.mskcc.org/?version=oncotree_2025_10_03&field=NAME&search=Dedifferentiated+Liposarcoma+%28DDLS%29"
        ]
      }
    }
  ],
  "extensions": [
    {
      "name": "solid_tumor",
      "value": true,
      "description": "Boolean value for if this tumor type is categorized as a solid tumor."
    }
  ],
  "primaryCoding": {
    "id": "coding:ncit:C3704",
    "code": "C3704",
    "name": "Dedifferentiated Liposarcoma",
    "system": "https://evsexplore.semantics.cancer.gov",
    "systemVersion": "26.08e",
    "iris": [
      "https://evsexplore.semantics.cancer.gov/evsexplore/concept/ncit/C3704"
    ]
  }
}

=== vanallenlab/moalmanac-db/dereferenced/diseases/dis_oncotree_TGCT.json
{
  "id": "dis:oncotree:TGCT",
  "conceptType": "Disease",
  "name": "Testicular Germ Cell Tumors",
  "mappings": [],
  "extensions": [
    {
      "name": "solid_tumor",
      "value": true,
      "description": "Boolean value for if this tumor type is categorized as a solid tumor."
    }
  ],
  "primaryCoding": {
    "id": "coding:oncotree:TGCT",
    "code": "TGCT",
    "name": "Testicular Germ Cell Tumors",
    "system": "https://oncotree.mskcc.org",
    "systemVersion": "oncotree_2021_11_02",
    "iris": [
      "https://oncotree.mskcc.org/?version=oncotree_2021_11_02&field=CODE&search=TGCT"
    ]
  }
}

=== vanallenlab/moalmanac-db/dereferenced/diseases/dis_oncotree_MBN.json
{
  "id": "dis:oncotree:MBN",
  "conceptType": "Disease",
  "name": "Mature B-Cell Neoplasms",
  "mappings": [],
  "extensions": [
    {
      "name": "solid_tumor",
      "value": false,
      "description": "Boolean value for if this tumor type is categorized as a solid tumor."
    }
  ],
  "primaryCoding": {
    "id": "coding:oncotree:MBN",
    "code": "MBN",
    "name": "Mature B-Cell Neoplasms",
    "system": "https://oncotree.mskcc.org",
    "systemVersion": "oncotree_2021_11_02",
    "iris": [
      "https://oncotree.mskcc.org/?version=oncotree_2021_11_02&field=CODE&search=MBN"
    ]
  }
}
