=== vanallenlab/moalmanac-db/schemas/dereferenced/documents.schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "https://moalmanac.org/schemas/dereferenced/documents.schema.json",
  "title": "Document",
  "description": "A source document. Publisher, company, drug names, dates, and status are extensions; urls are plain strings.",
  "type": "object",
  "properties": {
    "id": {
      "type": "string",
      "pattern": "^doc:(fda|ema|hse|hc|hpra):.+$"
    },
    "type": {
      "const": "Document"
    },
    "documentType": {
      "enum": [
        "Regulatory approval"
      ]
    },
    "name": {
      "type": "string"
    },
    "title": {
      "type": [
        "string",
        "null"
      ]
    },
    "aliases": {
      "type": "array",
      "items": {
        "type": "string"
      }
    },
    "description": {
      "type": "string"
    },
    "urls": {
      "type": "array",
      "items": {
        "type": "string",
        "format": "uri"
      }
    },
    "doi": {
      "type": [
        "string",
        "null"
      ]
    },
    "pmid": {
      "type": [
        "string",
        "null"
      ]
    },
    "extensions": {
      "type": "array",
      "items": {
        "anyOf": [
          {
            "$ref": "extension.schema.json",
            "properties": {
              "name": {
                "const": "agent"
              },
              "value": {
                "$ref": "agents.schema.json",
                "not": {
                  "required": [
                    "extensions"
                  ]
                }
              }
            }
          },
          {
            "$ref": "extension.schema.json",
            "properties": {
              "name": {
                "const": "company"
              },
              "value": {
                "type": "string"
              }
            }
          },
          {
            "$ref": "extension.schema.json",
            "properties": {
              "name": {
                "const": "drug_name_brand"
              },
              "value": {
                "type": [
                  "string",
                  "null"
                ]
              }
            }
          },
          {
            "$ref": "extension.schema.json",
            "properties": {
              "name": {
                "const": "drug_name_generic"
              },
              "value": {
                "type": [
                  "string",
                  "null"
                ]
              }
            }
          },
          {
            "$ref": "extension.schema.json",
            "properties": {
              "name": {
                "const": "first_publication_date"
              },
              "value": {
                "$ref": "#/$defs/iso_date_or_null"
              }
            }
          },
          {
            "$ref": "extension.schema.json",
            "properties": {
              "name": {
                "const": "publication_date"
              },
              "value": {
                "$ref": "#/$defs/iso_date_or_null"
              }
            }
          },
          {
            "$ref": "extension.schema.json",
            "properties": {
              "name": {
                "const": "regulatory_identifier"
              },
              "value": {
                "type": [
                  "string",
                  "null"
                ]
              }
            }
          },
          {
            "$ref": "extension.schema.json",
            "properties": {
              "name": {
                "const": "status"
              },
              "value": {
                "enum": [
                  "Active",
                  "Deprecated"
                ]
              }
            }
          }
        ]
      },
      "allOf": [
        {
          "contains": {
            "$ref": "extension.schema.json",
            "properties": {
              "name": {
                "const": "agent"
              },
              "value": {
                "$ref": "agents.schema.json",
                "not": {
                  "required": [
                    "extensions"
                  ]
                }
              }
            }
          }
        },
        {
          "contains": {
            "$ref": "extension.schema.json",
            "properties": {
              "name": {
                "const": "company"
              },
              "value": {
                "type": "string"
              }
            }
          }
        },
        {
          "contains": {
            "$ref": "extension.schema.json",
            "properties": {
              "name": {
                "const": "drug_name_brand"
              },
              "value": {
                "type": [
                  "string",
                  "null"
                ]
              }
            }
          }
        },
        {
          "contains": {
            "$ref": "extension.schema.json",
            "properties": {
              "name": {
                "const": "drug_name_generic"
              },
              "value": {
                "type": [
                  "string",
                  "null"
                ]
              }
            }
          }
        },
        {
          "contains": {
            "$ref": "extension.schema.json",
            "properties": {
              "name": {
                "const": "first_publication_date"
              },
              "value": {
                "$ref": "#/$defs/iso_date_or_null"
              }
            }
          }
        },
        {
          "contains": {
            "$ref": "extension.schema.json",
            "properties": {
              "name": {
                "const": "publication_date"
              },
              "value": {
                "$ref": "#/$defs/iso_date_or_null"
              }
            }
          }
        },
        {
          "contains": {
            "$ref": "extension.schema.json",
            "properties": {
              "name": {
                "const": "regulatory_identifier"
              },
              "value": {
                "type": [
                  "string",
                  "null"
                ]
              }
            }
          }
        },
        {
          "contains": {
            "$ref": "extension.schema.json",
            "properties": {
              "name": {
                "const": "status"
              },
              "value": {
                "enum": [
                  "Active",
                  "Deprecated"
                ]
              }
            }
          }
        }
      ]
    }
  },
  "required": [
    "id",
    "type",
    "documentType",
    "name",
    "title",
    "aliases",
    "description",
    "urls",
    "doi",
    "pmid",
    "extensions"
  ],
  "additionalProperties": false,
  "allOf": [
    {
      "if": {
        "required": [
          "id"
        ],
        "properties": {
          "id": {
            "pattern": "^doc:fda:"
          }
        }
      },
      "then": {
        "properties": {
          "extensions": {
            "contains": {
              "$ref": "extension.schema.json",
              "properties": {
                "name": {
                  "const": "regulatory_identifier"
                },
                "value": {
                  "type": "string",
                  "pattern": "^(BLA|NDA)[0-9]{6}$"
                }
              }
            }
          }
        }
      }
    }
  ],
  "$defs": {
    "iso_date_or_null": {
      "description": "An ISO 8601 date (YYYY-MM-DD) or null.",
      "oneOf": [
        {
          "type": "null"
        },
        {
          "type": "string",
          "format": "date"
        }
      ]
    }
  }
}

=== vanallenlab/moalmanac-db/dereferenced/documents/doc_hse_00823.json
{
  "id": "doc:hse:00823",
  "type": "Document",
  "documentType": "Regulatory approval",
  "name": "Tepotinib Therapy. NCCP National SACT Regimen. HSE.",
  "title": null,
  "aliases": [],
  "description": "Tepotinib Therapy, 2025, version number 2, NCCP National SACT Regimen, NCCP, viewed 26/03/2026, https://healthservice.hse.ie/documents/6868/823_V2_Tepotinib_Therapy.pdf",
  "urls": [
    "https://healthservice.hse.ie/documents/6868/823_V2_Tepotinib_Therapy.pdf"
  ],
  "doi": null,
  "pmid": null,
  "extensions": [
    {
      "name": "agent",
      "value": {
        "id": "agent:org:hse",
        "type": "Agent",
        "agentType": "organization",
        "name": "Health Service Executive",
        "description": "Regulatory agency that approves medicines for reimbursement by the public health system in the Republic of Ireland."
      },
      "description": "The organization that published this document."
    },
    {
      "name": "company",
      "value": "",
      "description": "The company that manufactures the cancer drug. Only applicable to market authorization documents."
    },
    {
      "name": "drug_name_brand",
      "value": null,
      "description": "The brand name of the cancer drug, per this document. Only applicable to market authorization documents."
    },
    {
      "name": "drug_name_generic",
      "value": null,
      "description": "The generic name of the cancer drug, per this document. Only applicable to market authorization documents."
    },
    {
      "name": "first_publication_date",
      "value": null,
      "description": "The publication date for the initial version of this document."
    },
    {
      "name": "publication_date",
      "value": "2024-08-01",
      "description": "The publication date for the document."
    },
    {
      "name": "regulatory_identifier",
      "value": null,
      "description": "Identifier assigned by the regulatory agency, such as an FDA application number (e.g. NDA208716, BLA125427) or an EMA product number (e.g. EMEA/H/C/006184)."
    },
    {
      "name": "status",
      "value": "Active",
      "description": "Whether this document is Active or Deprecated within moalmanac-db."
    }
  ]
}
