=== vanallenlab/moalmanac-db/schemas/dereferenced/propositions.schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "https://moalmanac.org/schemas/dereferenced/propositions.schema.json",
  "title": "Proposition",
  "description": "A VariantTherapeuticResponseProposition. Because Cat-VRS does not yet support sets of categorical variants, `subjectVariant` is a placeholder and the biomarker criteria are held in the `biomarkers` extension.",
  "type": "object",
  "properties": {
    "id": {
      "type": "string",
      "pattern": "^prop:vtxr:\\d+$"
    },
    "type": {
      "const": "VariantTherapeuticResponseProposition"
    },
    "predicate": {
      "enum": [
        "predictsSensitivityTo",
        "predictsResistanceTo"
      ]
    },
    "subjectVariant": {
      "type": "object",
      "properties": {
        "type": {
          "const": "CategoricalVariant"
        },
        "description": {
          "type": "string"
        }
      },
      "required": [
        "type",
        "description"
      ],
      "additionalProperties": false
    },
    "conditionQualifier": {
      "$ref": "diseases.schema.json"
    },
    "objectTherapeutic": {
      "oneOf": [
        {
          "$ref": "therapies.schema.json"
        },
        {
          "$ref": "therapy_groups.schema.json"
        }
      ]
    },
    "extensions": {
      "type": "array",
      "items": {
        "anyOf": [
          {
            "$ref": "extension.schema.json",
            "properties": {
              "name": {
                "const": "biomarkers"
              },
              "value": {
                "type": "array",
                "items": {
                  "$ref": "biomarker_criteria.schema.json"
                },
                "minItems": 1
              }
            }
          }
        ]
      },
      "allOf": [
        {
          "contains": {
            "$ref": "extension.schema.json",
            "properties": {
              "name": {
                "const": "biomarkers"
              },
              "value": {
                "type": "array",
                "items": {
                  "$ref": "biomarker_criteria.schema.json"
                },
                "minItems": 1
              }
            }
          }
        }
      ]
    }
  },
  "required": [
    "id",
    "type",
    "predicate",
    "subjectVariant",
    "conditionQualifier",
    "objectTherapeutic",
    "extensions"
  ],
  "additionalProperties": false
}

=== vanallenlab/moalmanac-db/dereferenced/propositions/prop_vtxr_369.json
{
  "id": "prop:vtxr:369",
  "type": "VariantTherapeuticResponseProposition",
  "predicate": "predictsSensitivityTo",
  "subjectVariant": {
    "type": "CategoricalVariant",
    "description": "Placeholder. Cat-VRS does not yet support sets of categorical variants. See the 'biomarkers' extension for biomarkers associated with this Proposition."
  },
  "conditionQualifier": {
    "id": "dis:ncit:C132146",
    "conceptType": "Disease",
    "name": "Any solid tumor",
    "mappings": [],
    "extensions": [
      {
        "name": "solid_tumor",
        "value": true,
        "description": "Boolean value for if this tumor type is categorized as a solid tumor."
      }
    ],
    "primaryCoding": {
      "id": "coding:ncit:C132146",
      "code": "C132146",
      "name": "Malignant Solid Neoplasm",
      "system": "https://evsexplore.semantics.cancer.gov",
      "systemVersion": "26.08e",
      "iris": [
        "https://evsexplore.semantics.cancer.gov/evsexplore/concept/ncit/C132146"
      ]
    }
  },
  "objectTherapeutic": {
    "id": "tx:ncit:C133821",
    "conceptType": "Therapy",
    "name": "Repotrectinib",
    "mappings": [
      {
        "relation": "relatedMatch",
        "coding": {
          "id": "coding:rxcui:2670644",
          "code": "2670644",
          "name": "repotrectinib",
          "system": "RxNorm",
          "systemVersion": "02-Mar-2026",
          "iris": [
            "https://mor.nlm.nih.gov/RxNav/search?searchBy=RXCUI&searchTerm=2670644"
          ]
        }
      },
      {
        "relation": "relatedMatch",
        "coding": {
          "id": "coding:omop:747362",
          "code": "747362",
          "name": "repotrectinib",
          "system": "OMOP",
          "systemVersion": "v20260227",
          "iris": [
            "https://athena.ohdsi.org/search-terms/terms/747362"
          ]
        }
      }
    ],
    "extensions": [
      {
        "name": "therapy_strategy",
        "value": [
          "ROS inhibition"
        ],
        "description": "Associated therapeutic strategy or mechanism of action of the therapy."
      },
      {
        "name": "therapy_type",
        "value": "Targeted therapy",
        "description": "Type of cancer treatment from cancer.gov: https://www.cancer.gov/about-cancer/treatment/types"
      }
    ],
    "primaryCoding": {
      "id": "coding:ncit:C133821",
      "code": "C133821",
      "name": "Repotrectinib",
      "system": "https://evsexplore.semantics.cancer.gov",
      "systemVersion": "26.08e",
      "iris": [
        "https://evsexplore.semantics.cancer.gov/evsexplore/concept/ncit/C133821"
      ]
    }
  },
  "extensions": [
    {
      "name": "biomarkers",
      "value": [
        {
          "id": "bmkr.criterion:63",
          "present": true,
          "subject": {
            "id": "bmkr:63",
            "type": "CategoricalVariant",
            "name": "v::NTRK1",
            "constraints": [
              {
                "type": "AdjacencyConstraint",
                "orderKnown": false,
                "adjoinedElements": [
                  {
                    "id": "gene:hgnc:8031",
                    "conceptType": "Gene",
                    "name": "NTRK1",
                    "primaryCoding": {
                      "id": "coding:hgnc:8031",
                      "code": "HGNC:8031",
                      "system": "https://genenames.org",
                      "iris": [
                        "https://www.genenames.org/data/gene-symbol-report/#!/hgnc_id/HGNC:8031"
                      ]
                    },
                    "mappings": [
                      {
                        "relation": "exactMatch",
                        "coding": {
                          "id": "coding:ensembl:ensg00000198400",
                          "code": "ENSG00000198400",
                          "system": "https://www.ensembl.org",
                          "iris": [
                            "https://www.ensembl.org/id/ENSG00000198400"
                          ]
                        }
                      },
                      {
                        "relation": "exactMatch",
                        "coding": {
                          "id": "coding:ncbi:4914",
                          "code": "4914",
                          "system": "https://www.ncbi.nlm.nih.gov/gene",
                          "iris": [
                            "https://www.ncbi.nlm.nih.gov/gene/4914"
                          ]
                        }
                      },
                      {
                        "relation": "relatedMatch",
                        "coding": {
                          "id": "coding:refseq:NM_002529.4",
                          "code": "NM_002529.4",
                          "system": "https://www.ncbi.nlm.nih.gov/nuccore",
                          "iris": [
                            "https://www.ncbi.nlm.nih.gov/nuccore/NM_002529.4"
                          ]
                        }
                      }
                    ]
                  },
                  {
                    "type": "UnspecifiedElement"
                  }
                ]
              }
            ],
            "extensions": [
              {
                "name": "biomarker_type",
                "value": "Gene fusion"
              }
            ]
          }
        }
      ],
      "description": "The biomarkers associated with this Proposition, each with a `present` flag indicating if the biomarker is present (true) or absent (false). Multiple biomarkers are combined with implied AND logic."
    }
  ]
}

=== vanallenlab/moalmanac-db/dereferenced/propositions/prop_vtxr_419.json
{
  "id": "prop:vtxr:419",
  "type": "VariantTherapeuticResponseProposition",
  "predicate": "predictsSensitivityTo",
  "subjectVariant": {
    "type": "CategoricalVariant",
    "description": "Placeholder. Cat-VRS does not yet support sets of categorical variants. See the 'biomarkers' extension for biomarkers associated with this Proposition."
  },
  "conditionQualifier": {
    "id": "dis:ncit:C203675",
    "conceptType": "Disease",
    "name": "Esophagogastric Adenocarcinoma",
    "mappings": [
      {
        "relation": "broadMatch",
        "coding": {
          "id": "coding:oncotree:EGC",
          "code": "EGC",
          "name": "Esophagogastric Adenocarcinoma",
          "system": "https://oncotree.mskcc.org",
          "systemVersion": "oncotree_2025_10_03",
          "iris": [
            "https://oncotree.mskcc.org/?version=oncotree_2025_10_03&field=NAME&search=Esophagogastric+Adenocarcinoma+%28EGC%29"
          ]
        }
      }
    ],
    "extensions": [
      {
        "name": "solid_tumor",
        "value": true,
        "description": "Boolean value for if this tumor type is categorized as a solid tumor."
      }
    ],
    "primaryCoding": {
      "id": "coding:ncit:C203675",
      "code": "C203675",
      "name": "Gastroesophageal Junction Carcinoma",
      "system": "https://evsexplore.semantics.cancer.gov",
      "systemVersion": "26.08e",
      "iris": [
        "https://evsexplore.semantics.cancer.gov/evsexplore/concept/ncit/C203675"
      ]
    }
  },
  "objectTherapeutic": {
    "id": "tx:ncit:C1647",
    "conceptType": "Therapy",
    "name": "Trastuzumab",
    "mappings": [
      {
        "relation": "relatedMatch",
        "coding": {
          "id": "coding:rxcui:224905",
          "code": "224905",
          "name": "trastuzumab",
          "system": "RxNorm",
          "systemVersion": "20250602",
          "iris": [
            "https://mor.nlm.nih.gov/RxNav/search?searchBy=RXCUI&searchTerm=224905"
          ]
        }
      },
      {
        "relation": "relatedMatch",
        "coding": {
          "id": "coding:omop:1387104",
          "code": "1387104",
          "name": "trastuzumab",
          "system": "OMOP",
          "systemVersion": "v20250827",
          "iris": [
            "https://athena.ohdsi.org/search-terms/terms/1387104"
          ]
        }
      }
    ],
    "extensions": [
      {
        "name": "therapy_strategy",
        "value": [
          "HER2 inhibition"
        ],
        "description": "Associated therapeutic strategy or mechanism of action of the therapy."
      },
      {
        "name": "therapy_type",
        "value": "Targeted therapy",
        "description": "Type of cancer treatment from cancer.gov: https://www.cancer.gov/about-cancer/treatment/types"
      }
    ],
    "primaryCoding": {
      "id": "coding:ncit:C1647",
      "code": "C1647",
      "name": "Trastuzumab",
      "system": "https://evsexplore.semantics.cancer.gov",
      "systemVersion": "26.08e",
      "iris": [
        "https://evsexplore.semantics.cancer.gov/evsexplore/concept/ncit/C1647"
      ]
    }
  },
  "extensions": [
    {
      "name": "biomarkers",
      "value": [
        {
          "id": "bmkr.criterion:20",
          "present": true,
          "subject": {
            "id": "bmkr:20",
            "type": "CategoricalVariant",
            "name": "HER2-positive",
            "constraints": [],
            "extensions": [
              {
                "name": "biomarker_type",
                "value": "Protein expression"
              },
              {
                "name": "marker",
                "value": "Human epidermal growth factor receptor 2 (HER2)"
              },
              {
                "name": "unit",
                "value": "status"
              },
              {
                "name": "equality",
                "value": "="
              },
              {
                "name": "value",
                "value": "Positive"
              }
            ]
          }
        }
      ],
      "description": "The biomarkers associated with this Proposition, each with a `present` flag indicating if the biomarker is present (true) or absent (false). Multiple biomarkers are combined with implied AND logic."
    }
  ]
}

=== vanallenlab/moalmanac-db/dereferenced/propositions/prop_vtxr_587.json
{
  "id": "prop:vtxr:587",
  "type": "VariantTherapeuticResponseProposition",
  "predicate": "predictsSensitivityTo",
  "subjectVariant": {
    "type": "CategoricalVariant",
    "description": "Placeholder. Cat-VRS does not yet support sets of categorical variants. See the 'biomarkers' extension for biomarkers associated with this Proposition."
  },
  "conditionQualifier": {
    "id": "dis:ncit:C7558",
    "conceptType": "Disease",
    "name": "Endometrial Carcinoma",
    "mappings": [
      {
        "relation": "exactMatch",
        "coding": {
          "id": "coding:oncotree:UCEC",
          "code": "UCEC",
          "name": "Endometrial Carcinoma",
          "system": "https://oncotree.mskcc.org",
          "systemVersion": "oncotree_2025_10_03",
          "iris": [
            "https://oncotree.mskcc.org/?version=oncotree_2025_10_03&field=NAME&search=Endometrial+Carcinoma+%28UCEC%29"
          ]
        }
      }
    ],
    "extensions": [
      {
        "name": "solid_tumor",
        "value": true,
        "description": "Boolean value for if this tumor type is categorized as a solid tumor."
      }
    ],
    "primaryCoding": {
      "id": "coding:ncit:C7558",
      "code": "C7558",
      "name": "Endometrial Carcinoma",
      "system": "https://evsexplore.semantics.cancer.gov",
      "systemVersion": "26.08e",
      "iris": [
        "https://evsexplore.semantics.cancer.gov/evsexplore/concept/ncit/C7558"
      ]
    }
  },
  "objectTherapeutic": {
    "id": "tx:ncit:C126799",
    "conceptType": "Therapy",
    "name": "Dostarlimab",
    "mappings": [
      {
        "relation": "relatedMatch",
        "coding": {
          "id": "coding:rxcui:2539967",
          "code": "2539967",
          "name": "dostarlimab",
          "system": "RxNorm",
          "systemVersion": "02-Mar-2026",
          "iris": [
            "https://mor.nlm.nih.gov/RxNav/search?searchBy=RXCUI&searchTerm=2539967"
          ]
        }
      },
      {
        "relation": "relatedMatch",
        "coding": {
          "id": "coding:omop:1536789",
          "code": "1536789",
          "name": "dostarlimab",
          "system": "OMOP",
          "systemVersion": "v20260227",
          "iris": [
            "https://athena.ohdsi.org/search-terms/terms/1536789"
          ]
        }
      },
      {
        "relation": "relatedMatch",
        "coding": {
          "id": "coding:omop:608113",
          "code": "608113",
          "name": "Dostarlimab",
          "system": "OMOP",
          "systemVersion": "v20260227",
          "iris": [
            "https://athena.ohdsi.org/search-terms/terms/608113"
          ]
        }
      }
    ],
    "extensions": [
      {
        "name": "therapy_strategy",
        "value": [
          "PD-1/PD-L1 inhibition"
        ],
        "description": "Associated therapeutic strategy or mechanism of action of the therapy."
      },
      {
        "name": "therapy_type",
        "value": "Immunotherapy",
        "description": "Type of cancer treatment from cancer.gov: https://www.cancer.gov/about-cancer/treatment/types"
      }
    ],
    "primaryCoding": {
      "id": "coding:ncit:C126799",
      "code": "C126799",
      "name": "Dostarlimab",
      "system": "https://evsexplore.semantics.cancer.gov",
      "systemVersion": "26.08e",
      "iris": [
        "https://evsexplore.semantics.cancer.gov/evsexplore/concept/ncit/C126799"
      ]
    }
  },
  "extensions": [
    {
      "name": "biomarkers",
      "value": [
        {
          "id": "bmkr.criterion:38",
          "present": true,
          "subject": {
            "id": "bmkr:38",
            "type": "CategoricalVariant",
            "name": "MSI-H",
            "constraints": [],
            "extensions": [
              {
                "name": "biomarker_type",
                "value": "Microsatellite stability"
              },
              {
                "name": "status",
                "value": "Microsatellite instability-high (MSI-H)"
              }
            ]
          }
        }
      ],
      "description": "The biomarkers associated with this Proposition, each with a `present` flag indicating if the biomarker is present (true) or absent (false). Multiple biomarkers are combined with implied AND logic."
    }
  ]
}

=== vanallenlab/moalmanac-db/dereferenced/propositions/prop_vtxr_330.json
{
  "id": "prop:vtxr:330",
  "type": "VariantTherapeuticResponseProposition",
  "predicate": "predictsSensitivityTo",
  "subjectVariant": {
    "type": "CategoricalVariant",
    "description": "Placeholder. Cat-VRS does not yet support sets of categorical variants. See the 'biomarkers' extension for biomarkers associated with this Proposition."
  },
  "conditionQualifier": {
    "id": "dis:ncit:C4025",
    "conceptType": "Disease",
    "name": "Esophageal Adenocarcinoma",
    "mappings": [
      {
        "relation": "exactMatch",
        "coding": {
          "id": "coding:oncotree:ESCA",
          "code": "ESCA",
          "name": "Esophageal Adenocarcinoma",
          "system": "https://oncotree.mskcc.org",
          "systemVersion": "oncotree_2025_10_03",
          "iris": [
            "https://oncotree.mskcc.org/?version=oncotree_2025_10_03&field=NAME&search=Esophageal+Adenocarcinoma+%28ESCA%29"
          ]
        }
      }
    ],
    "extensions": [
      {
        "name": "solid_tumor",
        "value": true,
        "description": "Boolean value for if this tumor type is categorized as a solid tumor."
      }
    ],
    "primaryCoding": {
      "id": "coding:ncit:C4025",
      "code": "C4025",
      "name": "Esophageal Adenocarcinoma",
      "system": "https://evsexplore.semantics.cancer.gov",
      "systemVersion": "26.08e",
      "iris": [
        "https://evsexplore.semantics.cancer.gov/evsexplore/concept/ncit/C4025"
      ]
    }
  },
  "objectTherapeutic": {
    "id": "tx:ncit:C106432",
    "conceptType": "Therapy",
    "name": "Pembrolizumab",
    "mappings": [
      {
        "relation": "relatedMatch",
        "coding": {
          "id": "coding:rxcui:1547545",
          "code": "1547545",
          "name": "pembrolizumab",
          "system": "RxNorm",
          "systemVersion": "02-Mar-2026",
          "iris": [
            "https://mor.nlm.nih.gov/RxNav/search?searchBy=RXCUI&searchTerm=1547545"
          ]
        }
      },
      {
        "relation": "relatedMatch",
        "coding": {
          "id": "coding:omop:45775965",
          "code": "45775965",
          "name": "pembrolizumab",
          "system": "OMOP",
          "systemVersion": "v20260227",
          "iris": [
            "https://athena.ohdsi.org/search-terms/terms/45775965"
          ]
        }
      },
      {
        "relation": "relatedMatch",
        "coding": {
          "id": "coding:omop:37396350",
          "code": "37396350",
          "name": "Pembrolizumab",
          "system": "OMOP",
          "systemVersion": "v20260227",
          "iris": [
            "https://athena.ohdsi.org/search-terms/terms/37396350"
          ]
        }
      }
    ],
    "extensions": [
      {
        "name": "therapy_strategy",
        "value": [
          "PD-1/PD-L1 inhibition"
        ],
        "description": "Associated therapeutic strategy or mechanism of action of the therapy."
      },
      {
        "name": "therapy_type",
        "value": "Immunotherapy",
        "description": "Type of cancer treatment from cancer.gov: https://www.cancer.gov/about-cancer/treatment/types"
      }
    ],
    "primaryCoding": {
      "id": "coding:ncit:C106432",
      "code": "C106432",
      "name": "Pembrolizumab",
      "system": "https://evsexplore.semantics.cancer.gov",
      "systemVersion": "26.08e",
      "iris": [
        "https://evsexplore.semantics.cancer.gov/evsexplore/concept/ncit/C106432"
      ]
    }
  },
  "extensions": [
    {
      "name": "biomarkers",
      "value": [
        {
          "id": "bmkr.criterion:41",
          "present": true,
          "subject": {
            "id": "bmkr:41",
            "type": "CategoricalVariant",
            "name": "PD-L1 (CPS) >= 10",
            "constraints": [],
            "extensions": [
              {
                "name": "biomarker_type",
                "value": "Protein expression"
              },
              {
                "name": "marker",
                "value": "PD-L1"
              },
              {
                "name": "unit",
                "value": "Combined Positive Score (CPS)"
              },
              {
                "name": "equality",
                "value": ">="
              },
              {
                "name": "value",
                "value": 10
              }
            ]
          }
        }
      ],
      "description": "The biomarkers associated with this Proposition, each with a `present` flag indicating if the biomarker is present (true) or absent (false). Multiple biomarkers are combined with implied AND logic."
    }
  ]
}
