=== vanallenlab/moalmanac-db/schemas/dereferenced/propositions.schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "https://moalmanac.org/schemas/dereferenced/propositions.schema.json",
  "title": "Proposition",
  "description": "A VariantTherapeuticResponseProposition. Because Cat-VRS does not yet support sets of categorical variants, `subjectVariant` is a placeholder and the biomarker criteria are held in the `biomarkers` extension.",
  "type": "object",
  "properties": {
    "id": {
      "type": "string",
      "pattern": "^prop:vtxr:\\d+$"
    },
    "type": {
      "const": "VariantTherapeuticResponseProposition"
    },
    "predicate": {
      "enum": [
        "predictsSensitivityTo",
        "predictsResistanceTo"
      ]
    },
    "subjectVariant": {
      "type": "object",
      "properties": {
        "type": {
          "const": "CategoricalVariant"
        },
        "description": {
          "type": "string"
        }
      },
      "required": [
        "type",
        "description"
      ],
      "additionalProperties": false
    },
    "conditionQualifier": {
      "$ref": "diseases.schema.json"
    },
    "objectTherapeutic": {
      "oneOf": [
        {
          "$ref": "therapies.schema.json"
        },
        {
          "$ref": "therapy_groups.schema.json"
        }
      ]
    },
    "extensions": {
      "type": "array",
      "items": {
        "anyOf": [
          {
            "$ref": "extension.schema.json",
            "properties": {
              "name": {
                "const": "biomarkers"
              },
              "value": {
                "type": "array",
                "items": {
                  "$ref": "biomarker_criteria.schema.json"
                },
                "minItems": 1
              }
            }
          }
        ]
      },
      "allOf": [
        {
          "contains": {
            "$ref": "extension.schema.json",
            "properties": {
              "name": {
                "const": "biomarkers"
              },
              "value": {
                "type": "array",
                "items": {
                  "$ref": "biomarker_criteria.schema.json"
                },
                "minItems": 1
              }
            }
          }
        }
      ]
    }
  },
  "required": [
    "id",
    "type",
    "predicate",
    "subjectVariant",
    "conditionQualifier",
    "objectTherapeutic",
    "extensions"
  ],
  "additionalProperties": false
}

=== vanallenlab/moalmanac-db/dereferenced/propositions/prop_vtxr_303.json
{
  "id": "prop:vtxr:303",
  "type": "VariantTherapeuticResponseProposition",
  "predicate": "predictsSensitivityTo",
  "subjectVariant": {
    "type": "CategoricalVariant",
    "description": "Placeholder. Cat-VRS does not yet support sets of categorical variants. See the 'biomarkers' extension for biomarkers associated with this Proposition."
  },
  "conditionQualifier": {
    "id": "dis:ncit:C3171",
    "conceptType": "Disease",
    "name": "Acute Myeloid Leukemia",
    "mappings": [
      {
        "relation": "exactMatch",
        "coding": {
          "id": "coding:oncotree:AML",
          "code": "AML",
          "name": "Acute Myeloid Leukemia",
          "system": "https://oncotree.mskcc.org",
          "systemVersion": "oncotree_2025_10_03",
          "iris": [
            "https://oncotree.mskcc.org/?version=oncotree_2025_10_03&field=NAME&search=Acute+Myeloid+Leukemia+%28AML%29"
          ]
        }
      }
    ],
    "extensions": [
      {
        "name": "solid_tumor",
        "value": false,
        "description": "Boolean value for if this tumor type is categorized as a solid tumor."
      }
    ],
    "primaryCoding": {
      "id": "coding:ncit:C3171",
      "code": "C3171",
      "name": "Acute Myeloid Leukemia",
      "system": "https://evsexplore.semantics.cancer.gov",
      "systemVersion": "26.08e",
      "iris": [
        "https://evsexplore.semantics.cancer.gov/evsexplore/concept/ncit/C3171"
      ]
    }
  },
  "objectTherapeutic": {
    "id": "tx:ncit:C129687",
    "conceptType": "Therapy",
    "name": "Olutasidenib",
    "mappings": [
      {
        "relation": "relatedMatch",
        "coding": {
          "id": "coding:rxcui:2623641",
          "code": "2623641",
          "name": "olutasidenib",
          "system": "RxNorm",
          "systemVersion": "02-Mar-2026",
          "iris": [
            "https://mor.nlm.nih.gov/RxNav/search?searchBy=RXCUI&searchTerm=2623641"
          ]
        }
      },
      {
        "relation": "relatedMatch",
        "coding": {
          "id": "coding:omop:742050",
          "code": "742050",
          "name": "olutasidenib",
          "system": "OMOP",
          "systemVersion": "v20260227",
          "iris": [
            "https://athena.ohdsi.org/search-terms/terms/742050"
          ]
        }
      }
    ],
    "extensions": [
      {
        "name": "therapy_strategy",
        "value": [
          "IDH1 inhibition"
        ],
        "description": "Associated therapeutic strategy or mechanism of action of the therapy."
      },
      {
        "name": "therapy_type",
        "value": "Targeted therapy",
        "description": "Type of cancer treatment from cancer.gov: https://www.cancer.gov/about-cancer/treatment/types"
      }
    ],
    "primaryCoding": {
      "id": "coding:ncit:C129687",
      "code": "C129687",
      "name": "Olutasidenib",
      "system": "https://evsexplore.semantics.cancer.gov",
      "systemVersion": "26.08e",
      "iris": [
        "https://evsexplore.semantics.cancer.gov/evsexplore/concept/ncit/C129687"
      ]
    }
  },
  "extensions": [
    {
      "name": "biomarkers",
      "value": [
        {
          "id": "bmkr.criterion:78",
          "present": true,
          "subject": {
            "id": "bmkr:78",
            "type": "CategoricalVariant",
            "name": "IDH1 p.R132S",
            "constraints": [
              {
                "type": "DefiningAlleleConstraint",
                "allele": {
                  "id": "ga4gh:VA.y-ioX4e_ySwP_LlplLNp0cz04a8BBr9H",
                  "type": "Allele",
                  "name": "NP_005887.2:p.Arg132Ser",
                  "aliases": [
                    "NP_005887.2:p.R132S",
                    "IDH1 p.R132S"
                  ],
                  "description": "VRS variation of NP_005887.2:p.Arg132Ser",
                  "digest": "y-ioX4e_ySwP_LlplLNp0cz04a8BBr9H",
                  "expressions": [
                    {
                      "syntax": "hgvs.p",
                      "value": "NP_005887.2:p.Arg132Ser",
                      "extensions": [
                        {
                          "name": "hgvs.p_short",
                          "value": "p.R132S"
                        }
                      ]
                    }
                  ],
                  "location": {
                    "id": "ga4gh:SL.c1wumiCWSPL2vagoeYClRf5Z1SuyrIdx",
                    "type": "SequenceLocation",
                    "name": null,
                    "aliases": [],
                    "description": "Amino acid position 132 of the Refseq protein NP_005887.2, which is the protein product of the MANE Select coding transcript for IDH1 (refseq:NM_005896.4).",
                    "digest": "c1wumiCWSPL2vagoeYClRf5Z1SuyrIdx",
                    "sequenceReference": {
                      "id": "ga4gh:SQ.VZMxTY2iB2G_EuwlpVZ0AnX6R-am08GZ",
                      "type": "SequenceReference",
                      "name": "NP_005887.2",
                      "aliases": [
                        "ensembl:ENSP00000260985.2",
                        "ga4gh:SQ.VZMxTY2iB2G_EuwlpVZ0AnX6R-am08GZ",
                        "refseq:NP_005887.2"
                      ],
                      "description": "The protein product of the MANE Select coding transcript for IDH1 (refseq:NM_005896.4), corresponding to the Refseq protein accession NP_005887.2.",
                      "moleculeType": "protein",
                      "refgetAccession": "SQ.VZMxTY2iB2G_EuwlpVZ0AnX6R-am08GZ",
                      "residueAlphabet": "aa"
                    },
                    "start": 131,
                    "end": 132,
                    "sequence": "R"
                  },
                  "state": {
                    "type": "LiteralSequenceExpression",
                    "sequence": "S"
                  }
                },
                "relations": []
              },
              {
                "type": "FeatureContextConstraint",
                "featureContext": {
                  "id": "gene:hgnc:5382",
                  "conceptType": "Gene",
                  "name": "IDH1",
                  "primaryCoding": {
                    "id": "coding:hgnc:5382",
                    "code": "HGNC:5382",
                    "system": "https://genenames.org",
                    "iris": [
                      "https://www.genenames.org/data/gene-symbol-report/#!/hgnc_id/HGNC:5382"
                    ]
                  },
                  "mappings": [
                    {
                      "relation": "exactMatch",
                      "coding": {
                        "id": "coding:ensembl:ensg00000138413",
                        "code": "ENSG00000138413",
                        "system": "https://www.ensembl.org",
                        "iris": [
                          "https://www.ensembl.org/id/ENSG00000138413"
                        ]
                      }
                    },
                    {
                      "relation": "exactMatch",
                      "coding": {
                        "id": "coding:ncbi:3417",
                        "code": "3417",
                        "system": "https://www.ncbi.nlm.nih.gov/gene",
                        "iris": [
                          "https://www.ncbi.nlm.nih.gov/gene/3417"
                        ]
                      }
                    },
                    {
                      "relation": "relatedMatch",
                      "coding": {
                        "id": "coding:refseq:NM_005896.4",
                        "code": "NM_005896.4",
                        "system": "https://www.ncbi.nlm.nih.gov/nuccore",
                        "iris": [
                          "https://www.ncbi.nlm.nih.gov/nuccore/NM_005896.4"
                        ]
                      }
                    }
                  ]
                }
              }
            ],
            "extensions": [
              {
                "name": "biomarker_type",
                "value": "Somatic variant"
              },
              {
                "name": "chromosome",
                "value": "2"
              },
              {
                "name": "start_position",
                "value": 209113113
              },
              {
                "name": "end_position",
                "value": 209113113
              },
              {
                "name": "reference_allele",
                "value": "G"
              },
              {
                "name": "alternate_allele",
                "value": "T"
              },
              {
                "name": "cdna_change",
                "value": "c.394C>A"
              },
              {
                "name": "protein_change",
                "value": "p.R132S"
              },
              {
                "name": "variant_annotation",
                "value": "Missense"
              },
              {
                "name": "exon",
                "value": 4
              },
              {
                "name": "rsid",
                "value": "rs121913499"
              },
              {
                "name": "hgvsg",
                "value": "2:g.209113113G>T"
              },
              {
                "name": "hgvsc",
                "value": "ENST00000345146.2:c.394C>A"
              }
            ]
          }
        }
      ],
      "description": "The biomarkers associated with this Proposition, each with a `present` flag indicating if the biomarker is present (true) or absent (false). Multiple biomarkers are combined with implied AND logic."
    }
  ]
}
