=== vanallenlab/moalmanac-db/schemas/dereferenced/sequence_locations.schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "https://moalmanac.org/schemas/dereferenced/sequence_locations.schema.json",
  "title": "SequenceLocation",
  "description": "A VRS SequenceLocation with its SequenceReference embedded.",
  "type": "object",
  "properties": {
    "id": {
      "type": "string",
      "pattern": "^ga4gh:SL\\.[A-Za-z0-9_-]{32}$"
    },
    "type": {
      "const": "SequenceLocation"
    },
    "name": {
      "type": [
        "string",
        "null"
      ]
    },
    "aliases": {
      "type": "array",
      "items": {
        "type": "string"
      }
    },
    "description": {
      "type": "string"
    },
    "digest": {
      "type": "string"
    },
    "sequenceReference": {
      "$ref": "sequence_references.schema.json"
    },
    "start": {
      "type": "integer",
      "minimum": 0
    },
    "end": {
      "type": "integer",
      "minimum": 0
    },
    "sequence": {
      "type": [
        "string",
        "null"
      ]
    }
  },
  "required": [
    "id",
    "type",
    "name",
    "aliases",
    "description",
    "digest",
    "sequenceReference",
    "start",
    "end",
    "sequence"
  ],
  "additionalProperties": false
}

=== vanallenlab/moalmanac-db/dereferenced/sequence_locations/ga4gh_SL.Lh4ivz9PI9DLGduOuQ6Fq8UI8CvamvtN.json
{
  "id": "ga4gh:SL.Lh4ivz9PI9DLGduOuQ6Fq8UI8CvamvtN",
  "type": "SequenceLocation",
  "name": null,
  "aliases": [],
  "description": "Sequence within refseq:NP_004110.2, the protein product of the MANE Select coding transcript for FLT3 (refseq:NM_004119.3), corresponding to Exon 8. This exon's protein location may share a codon boundary with the adjacent exon's protein location.",
  "digest": "Lh4ivz9PI9DLGduOuQ6Fq8UI8CvamvtN",
  "sequenceReference": {
    "id": "ga4gh:SQ.0dtDG7QKyvW7BntvQVpLS83mYRA58LKH",
    "type": "SequenceReference",
    "name": "NP_004110.2",
    "aliases": [
      "ensembl:ENSP00000241453.7",
      "ga4gh:SQ.0dtDG7QKyvW7BntvQVpLS83mYRA58LKH",
      "refseq:NP_004110.2"
    ],
    "description": "The protein product of the MANE Select coding transcript for FLT3 (refseq:NM_004119.3), corresponding to the Refseq protein accession NP_004110.2.",
    "moleculeType": "protein",
    "refgetAccession": "SQ.0dtDG7QKyvW7BntvQVpLS83mYRA58LKH",
    "residueAlphabet": "aa"
  },
  "start": 294,
  "end": 346,
  "sequence": null
}

=== vanallenlab/moalmanac-db/dereferenced/sequence_locations/ga4gh_SL.uWfFK_zQSzi5W6IoQJUGJMuNiKcP2AiW.json
{
  "id": "ga4gh:SL.uWfFK_zQSzi5W6IoQJUGJMuNiKcP2AiW",
  "type": "SequenceLocation",
  "name": null,
  "aliases": [],
  "description": "Sequence within refseq:NP_001365831.1, the protein product of the MANE Select coding transcript for ROS1 (refseq:NM_001378902.1), corresponding to Exon 30. This exon's protein location may share a codon boundary with the adjacent exon's protein location.",
  "digest": "uWfFK_zQSzi5W6IoQJUGJMuNiKcP2AiW",
  "sequenceReference": {
    "id": "ga4gh:SQ.22Sf5cMxU4cVHRP44TPGjT-lO17K4Dfc",
    "type": "SequenceReference",
    "name": "NP_001365831.1",
    "aliases": [
      "ensembl:ENSP00000357493.3",
      "ga4gh:SQ.22Sf5cMxU4cVHRP44TPGjT-lO17K4Dfc",
      "refseq:NP_001365831.1"
    ],
    "description": "The protein product of the MANE Select coding transcript for ROS1 (refseq:NM_001378902.1), corresponding to the Refseq protein accession NP_001365831.1.",
    "moleculeType": "protein",
    "refgetAccession": "SQ.22Sf5cMxU4cVHRP44TPGjT-lO17K4Dfc",
    "residueAlphabet": "aa"
  },
  "start": 1550,
  "end": 1628,
  "sequence": null
}

=== vanallenlab/moalmanac-db/dereferenced/sequence_locations/ga4gh_SL.AymiymWHURAm3uiKmFFaWiLW1QyBANhF.json
{
  "id": "ga4gh:SL.AymiymWHURAm3uiKmFFaWiLW1QyBANhF",
  "type": "SequenceLocation",
  "name": null,
  "aliases": [],
  "description": "Sequence within refseq:NM_000051.4, the MANE Select coding transcript for ATM, corresponding to Exon 4.",
  "digest": "AymiymWHURAm3uiKmFFaWiLW1QyBANhF",
  "sequenceReference": {
    "id": "ga4gh:SQ.XOHmaNgj4t4WeRzFBLzrbQG_pOe-qLOG",
    "type": "SequenceReference",
    "name": "NM_000051.4",
    "aliases": [
      "ga4gh:SQ.XOHmaNgj4t4WeRzFBLzrbQG_pOe-qLOG",
      "refseq:NM_000051.4"
    ],
    "description": "The MANE Select coding transcript for ATM, corresponding to the Refseq transcript accession NM_000051.4.",
    "moleculeType": "mRNA",
    "refgetAccession": "SQ.XOHmaNgj4t4WeRzFBLzrbQG_pOe-qLOG",
    "residueAlphabet": "na"
  },
  "start": 335,
  "end": 481,
  "sequence": null
}

=== vanallenlab/moalmanac-db/dereferenced/sequence_locations/ga4gh_SL.wMfDfZ79tSRoYOVXLgve2dSr2QwkCdgz.json
{
  "id": "ga4gh:SL.wMfDfZ79tSRoYOVXLgve2dSr2QwkCdgz",
  "type": "SequenceLocation",
  "name": null,
  "aliases": [],
  "description": "Sequence within refseq:NP_004295.2, the protein product of the MANE Select coding transcript for ALK (refseq:NM_004304.5), corresponding to Exon 15. This exon's protein location may share a codon boundary with the adjacent exon's protein location.",
  "digest": "wMfDfZ79tSRoYOVXLgve2dSr2QwkCdgz",
  "sequenceReference": {
    "id": "ga4gh:SQ.q9CnK-HKWh9eqhOi8FlzR7M0pCmUrWPs",
    "type": "SequenceReference",
    "name": "NP_004295.2",
    "aliases": [
      "ensembl:ENSP00000373700.3",
      "ga4gh:SQ.q9CnK-HKWh9eqhOi8FlzR7M0pCmUrWPs",
      "refseq:NP_004295.2"
    ],
    "description": "The protein product of the MANE Select coding transcript for ALK (refseq:NM_004304.5), corresponding to the Refseq protein accession NP_004295.2.",
    "moleculeType": "protein",
    "refgetAccession": "SQ.q9CnK-HKWh9eqhOi8FlzR7M0pCmUrWPs",
    "residueAlphabet": "aa"
  },
  "start": 829,
  "end": 878,
  "sequence": null
}

=== vanallenlab/moalmanac-db/dereferenced/sequence_locations/ga4gh_SL.1QfgR9A8fzzDcBuF-1RJDE72LGCFj60I.json
{
  "id": "ga4gh:SL.1QfgR9A8fzzDcBuF-1RJDE72LGCFj60I",
  "type": "SequenceLocation",
  "name": null,
  "aliases": [],
  "description": "Sequence within refseq:NP_001073981.1, the protein product of the MANE Select coding transcript for BICC1 (refseq:NM_001080512.3), corresponding to Exon 5.",
  "digest": "1QfgR9A8fzzDcBuF-1RJDE72LGCFj60I",
  "sequenceReference": {
    "id": "ga4gh:SQ._qQYOQ9IvNnke24f0-wy6ipO_dSY-aiD",
    "type": "SequenceReference",
    "name": "NP_001073981.1",
    "aliases": [
      "ensembl:ENSP00000362993.3",
      "ga4gh:SQ._qQYOQ9IvNnke24f0-wy6ipO_dSY-aiD",
      "refseq:NP_001073981.1"
    ],
    "description": "The protein product of the MANE Select coding transcript for BICC1 (refseq:NM_001080512.3), corresponding to the Refseq protein accession NP_001073981.1.",
    "moleculeType": "protein",
    "refgetAccession": "SQ._qQYOQ9IvNnke24f0-wy6ipO_dSY-aiD",
    "residueAlphabet": "aa"
  },
  "start": 129,
  "end": 182,
  "sequence": null
}

=== vanallenlab/moalmanac-db/dereferenced/sequence_locations/ga4gh_SL.blsYDimr6npxDY98UGDXLJHq-NWXY4hC.json
{
  "id": "ga4gh:SL.blsYDimr6npxDY98UGDXLJHq-NWXY4hC",
  "type": "SequenceLocation",
  "name": null,
  "aliases": [],
  "description": "Sequence within refseq:NP_000456.2, the protein product of the MANE Select coding transcript for BARD1 (refseq:NM_000465.4), corresponding to Exon 1. This exon's protein location may share a codon boundary with the adjacent exon's protein location.",
  "digest": "blsYDimr6npxDY98UGDXLJHq-NWXY4hC",
  "sequenceReference": {
    "id": "ga4gh:SQ.FHplLz13mAowCHRpfupULtsf4wMG2F0v",
    "type": "SequenceReference",
    "name": "NP_000456.2",
    "aliases": [
      "ensembl:ENSP00000260947.4",
      "ga4gh:SQ.FHplLz13mAowCHRpfupULtsf4wMG2F0v",
      "refseq:NP_000456.2"
    ],
    "description": "The protein product of the MANE Select coding transcript for BARD1 (refseq:NM_000465.4), corresponding to the Refseq protein accession NP_000456.2.",
    "moleculeType": "protein",
    "refgetAccession": "SQ.FHplLz13mAowCHRpfupULtsf4wMG2F0v",
    "residueAlphabet": "aa"
  },
  "start": 0,
  "end": 53,
  "sequence": null
}

=== vanallenlab/moalmanac-db/dereferenced/sequence_locations/ga4gh_SL.QTK-WZWUSrNDxpvsD45KgNiaDXIetFZK.json
{
  "id": "ga4gh:SL.QTK-WZWUSrNDxpvsD45KgNiaDXIetFZK",
  "type": "SequenceLocation",
  "name": null,
  "aliases": [],
  "description": "Sequence within refseq:NM_004327.4, the MANE Select coding transcript for BCR, corresponding to Exon 17.",
  "digest": "QTK-WZWUSrNDxpvsD45KgNiaDXIetFZK",
  "sequenceReference": {
    "id": "ga4gh:SQ.kpytJsXw3BwLC3oBSjHQS1kwxs4WO3I3",
    "type": "SequenceReference",
    "name": "NM_004327.4",
    "aliases": [
      "ensembl:ENST00000305877.13",
      "ga4gh:SQ.kpytJsXw3BwLC3oBSjHQS1kwxs4WO3I3",
      "refseq:NM_004327.4"
    ],
    "description": "The MANE Select coding transcript for BCR, corresponding to the Refseq transcript accession NM_004327.4.",
    "moleculeType": "mRNA",
    "refgetAccession": "SQ.kpytJsXw3BwLC3oBSjHQS1kwxs4WO3I3",
    "residueAlphabet": "na"
  },
  "start": 3464,
  "end": 3524,
  "sequence": null
}

=== vanallenlab/moalmanac-db/dereferenced/sequence_locations/ga4gh_SL.dmYjH2VJr352a3ZxdkEpW51gv2hFXVAu.json
{
  "id": "ga4gh:SL.dmYjH2VJr352a3ZxdkEpW51gv2hFXVAu",
  "type": "SequenceLocation",
  "name": null,
  "aliases": [],
  "description": "Sequence within refseq:NP_075598.2, the protein product of the MANE Select coding transcript for FGFR1 (refseq:NM_023110.3), corresponding to Exon 18.",
  "digest": "dmYjH2VJr352a3ZxdkEpW51gv2hFXVAu",
  "sequenceReference": {
    "id": "ga4gh:SQ.fgaUDXKfU18Tt8FUC5-BeWqLIEhEdMZ-",
    "type": "SequenceReference",
    "name": "NP_075598.2",
    "aliases": [
      "ensembl:ENSP00000400162.2",
      "ga4gh:SQ.fgaUDXKfU18Tt8FUC5-BeWqLIEhEdMZ-",
      "refseq:NP_075598.2"
    ],
    "description": "The protein product of the MANE Select coding transcript for FGFR1 (refseq:NM_023110.3), corresponding to the Refseq protein accession NP_075598.2.",
    "moleculeType": "protein",
    "refgetAccession": "SQ.fgaUDXKfU18Tt8FUC5-BeWqLIEhEdMZ-",
    "residueAlphabet": "aa"
  },
  "start": 764,
  "end": 822,
  "sequence": null
}
