=== vanallenlab/moalmanac-db/schemas/dereferenced/sequence_references.schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "https://moalmanac.org/schemas/dereferenced/sequence_references.schema.json",
  "title": "SequenceReference",
  "description": "A VRS SequenceReference: a reference sequence (protein, transcript, or chromosome).",
  "type": "object",
  "properties": {
    "id": {
      "type": "string",
      "pattern": "^ga4gh:SQ\\.[A-Za-z0-9_-]{32}$"
    },
    "type": {
      "const": "SequenceReference"
    },
    "name": {
      "type": "string"
    },
    "aliases": {
      "type": "array",
      "items": {
        "type": "string"
      }
    },
    "description": {
      "type": "string"
    },
    "moleculeType": {
      "enum": [
        "protein",
        "mRNA",
        "genomic"
      ]
    },
    "refgetAccession": {
      "type": "string",
      "pattern": "^SQ\\.[A-Za-z0-9_-]{32}$"
    },
    "residueAlphabet": {
      "enum": [
        "aa",
        "na"
      ]
    }
  },
  "required": [
    "id",
    "type",
    "name",
    "aliases",
    "description",
    "moleculeType",
    "refgetAccession",
    "residueAlphabet"
  ],
  "additionalProperties": false
}

=== vanallenlab/moalmanac-db/dereferenced/sequence_references/ga4gh_SQ.bcXSOLv4TaKocnaHlHdoyFiFIHNWYxt7.json
{
  "id": "ga4gh:SQ.bcXSOLv4TaKocnaHlHdoyFiFIHNWYxt7",
  "type": "SequenceReference",
  "name": "NP_061330.2",
  "aliases": [
    "ensembl:ENSP00000005260.8",
    "ga4gh:SQ.bcXSOLv4TaKocnaHlHdoyFiFIHNWYxt7",
    "refseq:NP_061330.2"
  ],
  "description": "The protein product of the MANE Select coding transcript for BAIAP2L1 (refseq:NM_018842.5), corresponding to the Refseq protein accession NP_061330.2.",
  "moleculeType": "protein",
  "refgetAccession": "SQ.bcXSOLv4TaKocnaHlHdoyFiFIHNWYxt7",
  "residueAlphabet": "aa"
}

=== vanallenlab/moalmanac-db/dereferenced/sequence_references/ga4gh_SQ.GMP4RuPu7Q_irnmwoRIbnsFiecXnnHlw.json
{
  "id": "ga4gh:SQ.GMP4RuPu7Q_irnmwoRIbnsFiecXnnHlw",
  "type": "SequenceReference",
  "name": "NP_478123.1",
  "aliases": [
    "ensembl:ENSP00000336701.4",
    "ga4gh:SQ.GMP4RuPu7Q_irnmwoRIbnsFiecXnnHlw",
    "refseq:NP_478123.1"
  ],
  "description": "The protein product of the MANE Select coding transcript for RAD51C (refseq:NM_058216.3), corresponding to the Refseq protein accession NP_478123.1.",
  "moleculeType": "protein",
  "refgetAccession": "SQ.GMP4RuPu7Q_irnmwoRIbnsFiecXnnHlw",
  "residueAlphabet": "aa"
}

=== vanallenlab/moalmanac-db/dereferenced/sequence_references/ga4gh_SQ.7B7SHsmchAR0dFcDCuSFjJAo7tX87krQ.json
{
  "id": "ga4gh:SQ.7B7SHsmchAR0dFcDCuSFjJAo7tX87krQ",
  "type": "SequenceReference",
  "name": "NC_000022.11",
  "aliases": [
    "ga4gh:SQ.7B7SHsmchAR0dFcDCuSFjJAo7tX87krQ",
    "refseq:NC_000022.11"
  ],
  "description": "GRCh38 chromosome 22 (RefSeq NC_000022.11).",
  "moleculeType": "genomic",
  "refgetAccession": "SQ.7B7SHsmchAR0dFcDCuSFjJAo7tX87krQ",
  "residueAlphabet": "na"
}
