=== vanallenlab/moalmanac-db/schemas/dereferenced/sequence_locations.schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "https://moalmanac.org/schemas/dereferenced/sequence_locations.schema.json",
  "title": "SequenceLocation",
  "description": "A VRS SequenceLocation with its SequenceReference embedded.",
  "type": "object",
  "properties": {
    "id": {
      "type": "string",
      "pattern": "^ga4gh:SL\\.[A-Za-z0-9_-]{32}$"
    },
    "type": {
      "const": "SequenceLocation"
    },
    "name": {
      "type": [
        "string",
        "null"
      ]
    },
    "aliases": {
      "type": "array",
      "items": {
        "type": "string"
      }
    },
    "description": {
      "type": "string"
    },
    "digest": {
      "type": "string"
    },
    "sequenceReference": {
      "$ref": "sequence_references.schema.json"
    },
    "start": {
      "type": "integer",
      "minimum": 0
    },
    "end": {
      "type": "integer",
      "minimum": 0
    },
    "sequence": {
      "type": [
        "string",
        "null"
      ]
    }
  },
  "required": [
    "id",
    "type",
    "name",
    "aliases",
    "description",
    "digest",
    "sequenceReference",
    "start",
    "end",
    "sequence"
  ],
  "additionalProperties": false
}

=== vanallenlab/moalmanac-db/dereferenced/sequence_locations/ga4gh_SL.3Yyid_s8qUGnUzdLWeWjWpLT_1TTl-tD.json
{
  "id": "ga4gh:SL.3Yyid_s8qUGnUzdLWeWjWpLT_1TTl-tD",
  "type": "SequenceLocation",
  "name": null,
  "aliases": [],
  "description": "Sequence within refseq:NP_000042.3, the protein product of the MANE Select coding transcript for ATM (refseq:NM_000051.4), corresponding to Exon 8. This exon's protein location may share a codon boundary with the adjacent exon's protein location.",
  "digest": "3Yyid_s8qUGnUzdLWeWjWpLT_1TTl-tD",
  "sequenceReference": {
    "id": "ga4gh:SQ.6k1y4bTo7pEJ-a1GaniRBaCJXXGkBGFO",
    "type": "SequenceReference",
    "name": "NP_000042.3",
    "aliases": [
      "ensembl:ENSP00000278616.4",
      "ga4gh:SQ.6k1y4bTo7pEJ-a1GaniRBaCJXXGkBGFO",
      "refseq:NP_000042.3"
    ],
    "description": "The protein product of the MANE Select coding transcript for ATM (refseq:NM_000051.4), corresponding to the Refseq protein accession NP_000042.3.",
    "moleculeType": "protein",
    "refgetAccession": "SQ.6k1y4bTo7pEJ-a1GaniRBaCJXXGkBGFO",
    "residueAlphabet": "aa"
  },
  "start": 300,
  "end": 355,
  "sequence": null
}

=== vanallenlab/moalmanac-db/dereferenced/sequence_locations/ga4gh_SL.SZJQHxsheey3jCU8R4e9h2kW14Ki6Juu.json
{
  "id": "ga4gh:SL.SZJQHxsheey3jCU8R4e9h2kW14Ki6Juu",
  "type": "SequenceLocation",
  "name": null,
  "aliases": [],
  "description": "Sequence within refseq:NP_000050.3, the protein product of the MANE Select coding transcript for BRCA2 (refseq:NM_000059.4), corresponding to Exon 26.",
  "digest": "SZJQHxsheey3jCU8R4e9h2kW14Ki6Juu",
  "sequenceReference": {
    "id": "ga4gh:SQ.A6rzuv6kdsuIp6gy6fykzgzyJe9NJOC9",
    "type": "SequenceReference",
    "name": "NP_000050.3",
    "aliases": [
      "ensembl:ENSP00000369497.3",
      "ga4gh:SQ.A6rzuv6kdsuIp6gy6fykzgzyJe9NJOC9",
      "refseq:NP_000050.3"
    ],
    "description": "The protein product of the MANE Select coding transcript for BRCA2 (refseq:NM_000059.4), corresponding to the Refseq protein accession NP_000050.3.",
    "moleculeType": "protein",
    "refgetAccession": "SQ.A6rzuv6kdsuIp6gy6fykzgzyJe9NJOC9",
    "residueAlphabet": "aa"
  },
  "start": 3167,
  "end": 3216,
  "sequence": null
}

=== vanallenlab/moalmanac-db/dereferenced/sequence_locations/ga4gh_SL.0yTzdHkVxvxwVXgahyllpsou3QjkThd4.json
{
  "id": "ga4gh:SL.0yTzdHkVxvxwVXgahyllpsou3QjkThd4",
  "type": "SequenceLocation",
  "name": null,
  "aliases": [],
  "description": "Sequence within refseq:NP_112179.2, the protein product of the MANE Select coding transcript for FIP1L1 (refseq:NM_030917.4), corresponding to Exon 8. This exon's protein location may share a codon boundary with the adjacent exon's protein location.",
  "digest": "0yTzdHkVxvxwVXgahyllpsou3QjkThd4",
  "sequenceReference": {
    "id": "ga4gh:SQ.l_Fbxn4URDKhZEq4FkZCL_kL7yqbsKjL",
    "type": "SequenceReference",
    "name": "NP_112179.2",
    "aliases": [
      "ensembl:ENSP00000336752.6",
      "ga4gh:SQ.l_Fbxn4URDKhZEq4FkZCL_kL7yqbsKjL",
      "refseq:NP_112179.2"
    ],
    "description": "The protein product of the MANE Select coding transcript for FIP1L1 (refseq:NM_030917.4), corresponding to the Refseq protein accession NP_112179.2.",
    "moleculeType": "protein",
    "refgetAccession": "SQ.l_Fbxn4URDKhZEq4FkZCL_kL7yqbsKjL",
    "residueAlphabet": "aa"
  },
  "start": 168,
  "end": 212,
  "sequence": null
}

=== vanallenlab/moalmanac-db/dereferenced/sequence_locations/ga4gh_SL.LAu3Yx5-C9NGEhzFqKKQ3CupAOmk9wMU.json
{
  "id": "ga4gh:SL.LAu3Yx5-C9NGEhzFqKKQ3CupAOmk9wMU",
  "type": "SequenceLocation",
  "name": null,
  "aliases": [],
  "description": "Sequence within refseq:NP_005887.2, the protein product of the MANE Select coding transcript for IDH1 (refseq:NM_005896.4), corresponding to Exon 3. This exon's protein location may share a codon boundary with the adjacent exon's protein location.",
  "digest": "LAu3Yx5-C9NGEhzFqKKQ3CupAOmk9wMU",
  "sequenceReference": {
    "id": "ga4gh:SQ.VZMxTY2iB2G_EuwlpVZ0AnX6R-am08GZ",
    "type": "SequenceReference",
    "name": "NP_005887.2",
    "aliases": [
      "ensembl:ENSP00000260985.2",
      "ga4gh:SQ.VZMxTY2iB2G_EuwlpVZ0AnX6R-am08GZ",
      "refseq:NP_005887.2"
    ],
    "description": "The protein product of the MANE Select coding transcript for IDH1 (refseq:NM_005896.4), corresponding to the Refseq protein accession NP_005887.2.",
    "moleculeType": "protein",
    "refgetAccession": "SQ.VZMxTY2iB2G_EuwlpVZ0AnX6R-am08GZ",
    "residueAlphabet": "aa"
  },
  "start": 0,
  "end": 41,
  "sequence": null
}

=== vanallenlab/moalmanac-db/dereferenced/sequence_locations/ga4gh_SL.gyhCM2MFxeFc9EPkoAtBvOhy1MGnKGqn.json
{
  "id": "ga4gh:SL.gyhCM2MFxeFc9EPkoAtBvOhy1MGnKGqn",
  "type": "SequenceLocation",
  "name": null,
  "aliases": [],
  "description": "Sequence spanning the length of refseq:NM_013964.5, the MANE Select coding transcript for NRG1.",
  "digest": "gyhCM2MFxeFc9EPkoAtBvOhy1MGnKGqn",
  "sequenceReference": {
    "id": "ga4gh:SQ.OPVeJm9T3KcdeHmV_EI5RbIhnEnLm2O4",
    "type": "SequenceReference",
    "name": "NM_013964.5",
    "aliases": [
      "ga4gh:SQ.OPVeJm9T3KcdeHmV_EI5RbIhnEnLm2O4",
      "refseq:NM_013964.5"
    ],
    "description": "The MANE Select coding transcript for NRG1, corresponding to the Refseq transcript accession NM_013964.5.",
    "moleculeType": "mRNA",
    "refgetAccession": "SQ.OPVeJm9T3KcdeHmV_EI5RbIhnEnLm2O4",
    "residueAlphabet": "na"
  },
  "start": 0,
  "end": 11983,
  "sequence": null
}

=== vanallenlab/moalmanac-db/dereferenced/sequence_locations/ga4gh_SL.weJjqdxQd0V9YpVFidaRZx-JTzpxbfMj.json
{
  "id": "ga4gh:SL.weJjqdxQd0V9YpVFidaRZx-JTzpxbfMj",
  "type": "SequenceLocation",
  "name": null,
  "aliases": [],
  "description": "Sequence within refseq:NP_006209.2, the protein product of the MANE Select coding transcript for PIK3CA (refseq:NM_006218.4), corresponding to Exon 19. This exon's protein location may share a codon boundary with the adjacent exon's protein location.",
  "digest": "weJjqdxQd0V9YpVFidaRZx-JTzpxbfMj",
  "sequenceReference": {
    "id": "ga4gh:SQ.km8C9FORJbErpAh7Ub63pZLUzEm-au9D",
    "type": "SequenceReference",
    "name": "NP_006209.2",
    "aliases": [
      "ensembl:ENSP00000263967.3",
      "ga4gh:SQ.km8C9FORJbErpAh7Ub63pZLUzEm-au9D",
      "refseq:NP_006209.2"
    ],
    "description": "The protein product of the MANE Select coding transcript for PIK3CA (refseq:NM_006218.4), corresponding to the Refseq protein accession NP_006209.2.",
    "moleculeType": "protein",
    "refgetAccession": "SQ.km8C9FORJbErpAh7Ub63pZLUzEm-au9D",
    "residueAlphabet": "aa"
  },
  "start": 888,
  "end": 928,
  "sequence": null
}

=== vanallenlab/moalmanac-db/dereferenced/sequence_locations/ga4gh_SL.1ZWJnKt_UlGqtFbWds59xxNiYWbqEY9T.json
{
  "id": "ga4gh:SL.1ZWJnKt_UlGqtFbWds59xxNiYWbqEY9T",
  "type": "SequenceLocation",
  "name": null,
  "aliases": [],
  "description": "Sequence within refseq:NP_001184033.1, the protein product of the MANE Select coding transcript for KMT2A (refseq:NM_001197104.2), corresponding to Exon 28. This exon's protein location shares a codon boundary with the adjacent exons on both sides.",
  "digest": "1ZWJnKt_UlGqtFbWds59xxNiYWbqEY9T",
  "sequenceReference": {
    "id": "ga4gh:SQ.AxiFiHR1KWySlGgSpw28vKBbBXfXEKcq",
    "type": "SequenceReference",
    "name": "NP_001184033.1",
    "aliases": [
      "ensembl:ENSP00000436786.1",
      "ga4gh:SQ.AxiFiHR1KWySlGgSpw28vKBbBXfXEKcq",
      "refseq:NP_001184033.1"
    ],
    "description": "The protein product of the MANE Select coding transcript for KMT2A (refseq:NM_001197104.2), corresponding to the Refseq protein accession NP_001184033.1.",
    "moleculeType": "protein",
    "refgetAccession": "SQ.AxiFiHR1KWySlGgSpw28vKBbBXfXEKcq",
    "residueAlphabet": "aa"
  },
  "start": 3584,
  "end": 3612,
  "sequence": null
}

=== vanallenlab/moalmanac-db/dereferenced/sequence_locations/ga4gh_SL.Ne7JO0zFytoMvuN9c2WJTYWTyfzhBLXi.json
{
  "id": "ga4gh:SL.Ne7JO0zFytoMvuN9c2WJTYWTyfzhBLXi",
  "type": "SequenceLocation",
  "name": null,
  "aliases": [],
  "description": "Sequence spanning the length of refseq:NM_002168.4, the MANE Select coding transcript for IDH2.",
  "digest": "Ne7JO0zFytoMvuN9c2WJTYWTyfzhBLXi",
  "sequenceReference": {
    "id": "ga4gh:SQ.kirLjhm3sLodOO90EOQJ9e41ZMcln-Q6",
    "type": "SequenceReference",
    "name": "NM_002168.4",
    "aliases": [
      "ga4gh:SQ.kirLjhm3sLodOO90EOQJ9e41ZMcln-Q6",
      "refseq:NM_002168.4"
    ],
    "description": "The MANE Select coding transcript for IDH2, corresponding to the Refseq transcript accession NM_002168.4.",
    "moleculeType": "mRNA",
    "refgetAccession": "SQ.kirLjhm3sLodOO90EOQJ9e41ZMcln-Q6",
    "residueAlphabet": "na"
  },
  "start": 0,
  "end": 2658,
  "sequence": null
}
