=== vanallenlab/moalmanac-db/schemas/dereferenced/sequence_locations.schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "https://moalmanac.org/schemas/dereferenced/sequence_locations.schema.json",
  "title": "SequenceLocation",
  "description": "A VRS SequenceLocation with its SequenceReference embedded.",
  "type": "object",
  "properties": {
    "id": {
      "type": "string",
      "pattern": "^ga4gh:SL\\.[A-Za-z0-9_-]{32}$"
    },
    "type": {
      "const": "SequenceLocation"
    },
    "name": {
      "type": [
        "string",
        "null"
      ]
    },
    "aliases": {
      "type": "array",
      "items": {
        "type": "string"
      }
    },
    "description": {
      "type": "string"
    },
    "digest": {
      "type": "string"
    },
    "sequenceReference": {
      "$ref": "sequence_references.schema.json"
    },
    "start": {
      "type": "integer",
      "minimum": 0
    },
    "end": {
      "type": "integer",
      "minimum": 0
    },
    "sequence": {
      "type": [
        "string",
        "null"
      ]
    }
  },
  "required": [
    "id",
    "type",
    "name",
    "aliases",
    "description",
    "digest",
    "sequenceReference",
    "start",
    "end",
    "sequence"
  ],
  "additionalProperties": false
}

=== vanallenlab/moalmanac-db/dereferenced/sequence_locations/ga4gh_SL.VvxtKHfg97EU8GhA19ohjVa484O3i_he.json
{
  "id": "ga4gh:SL.VvxtKHfg97EU8GhA19ohjVa484O3i_he",
  "type": "SequenceLocation",
  "name": null,
  "aliases": [],
  "description": "Sequence within refseq:NP_005582.1, the protein product of the MANE Select coding transcript for MRE11 (refseq:NM_005591.4), corresponding to Exon 8. This exon's protein location shares a codon boundary with the adjacent exons on both sides.",
  "digest": "VvxtKHfg97EU8GhA19ohjVa484O3i_he",
  "sequenceReference": {
    "id": "ga4gh:SQ.38K-KnPP6NQiu2DBp511BJVGW-kodzxW",
    "type": "SequenceReference",
    "name": "NP_005582.1",
    "aliases": [
      "ensembl:ENSP00000325863.3",
      "ga4gh:SQ.38K-KnPP6NQiu2DBp511BJVGW-kodzxW",
      "refseq:NP_005582.1"
    ],
    "description": "The protein product of the MANE Select coding transcript for MRE11 (refseq:NM_005591.4), corresponding to the Refseq protein accession NP_005582.1.",
    "moleculeType": "protein",
    "refgetAccession": "SQ.38K-KnPP6NQiu2DBp511BJVGW-kodzxW",
    "residueAlphabet": "aa"
  },
  "start": 219,
  "end": 282,
  "sequence": null
}

=== vanallenlab/moalmanac-db/dereferenced/sequence_locations/ga4gh_SL.qjXrBOZkuGVo7s7XxqL_95Cz5lKUJYMD.json
{
  "id": "ga4gh:SL.qjXrBOZkuGVo7s7XxqL_95Cz5lKUJYMD",
  "type": "SequenceLocation",
  "name": null,
  "aliases": [],
  "description": "Sequence within refseq:NM_057091.3, the MANE Select coding transcript for NBN, corresponding to Exon 1.",
  "digest": "qjXrBOZkuGVo7s7XxqL_95Cz5lKUJYMD",
  "sequenceReference": {
    "id": "ga4gh:SQ.EKPoUVT6-4jjrWBzGGKMGEYxc2bkajSc",
    "type": "SequenceReference",
    "name": "NM_057091.3",
    "aliases": [
      "ensembl:ENST00000372359.10",
      "ga4gh:SQ.EKPoUVT6-4jjrWBzGGKMGEYxc2bkajSc",
      "refseq:NM_057091.3"
    ],
    "description": "The MANE Select coding transcript for NBN, corresponding to the Refseq transcript accession NM_057091.3.",
    "moleculeType": "mRNA",
    "refgetAccession": "SQ.EKPoUVT6-4jjrWBzGGKMGEYxc2bkajSc",
    "residueAlphabet": "na"
  },
  "start": 0,
  "end": 85,
  "sequence": null
}

=== vanallenlab/moalmanac-db/dereferenced/sequence_locations/ga4gh_SL.5nmqCqFD-sKI5lFRHOfbFIg7Arrk3lW3.json
{
  "id": "ga4gh:SL.5nmqCqFD-sKI5lFRHOfbFIg7Arrk3lW3",
  "type": "SequenceLocation",
  "name": null,
  "aliases": [],
  "description": "Sequence within refseq:NM_000142.5, the MANE Select coding transcript for FGFR3, corresponding to Exon 13.",
  "digest": "5nmqCqFD-sKI5lFRHOfbFIg7Arrk3lW3",
  "sequenceReference": {
    "id": "ga4gh:SQ.K_-bl-z6BuaqSy_vjZyjunOVEMoYG7VX",
    "type": "SequenceReference",
    "name": "NM_000142.5",
    "aliases": [
      "ga4gh:SQ.K_-bl-z6BuaqSy_vjZyjunOVEMoYG7VX",
      "refseq:NM_000142.5"
    ],
    "description": "The MANE Select coding transcript for FGFR3, corresponding to the Refseq transcript accession NM_000142.5.",
    "moleculeType": "mRNA",
    "refgetAccession": "SQ.K_-bl-z6BuaqSy_vjZyjunOVEMoYG7VX",
    "residueAlphabet": "na"
  },
  "start": 1920,
  "end": 2111,
  "sequence": null
}

=== vanallenlab/moalmanac-db/dereferenced/sequence_locations/ga4gh_SL.qejOzbeORizxJQg1x_lidIaLTnb1wscQ.json
{
  "id": "ga4gh:SL.qejOzbeORizxJQg1x_lidIaLTnb1wscQ",
  "type": "SequenceLocation",
  "name": null,
  "aliases": [],
  "description": "Sequence within refseq:NP_006197.1, the protein product of the MANE Select coding transcript for PDGFRA (refseq:NM_006206.6), corresponding to Exon 23. This exon's protein location may share a codon boundary with the adjacent exon's protein location.",
  "digest": "qejOzbeORizxJQg1x_lidIaLTnb1wscQ",
  "sequenceReference": {
    "id": "ga4gh:SQ.XpQn9sZLGv_GU3uiWO7YHq9-_alGjrVX",
    "type": "SequenceReference",
    "name": "NP_006197.1",
    "aliases": [
      "ensembl:ENSP00000257290.5",
      "ga4gh:SQ.XpQn9sZLGv_GU3uiWO7YHq9-_alGjrVX",
      "refseq:NP_006197.1"
    ],
    "description": "The protein product of the MANE Select coding transcript for PDGFRA (refseq:NM_006206.6), corresponding to the Refseq protein accession NP_006197.1.",
    "moleculeType": "protein",
    "refgetAccession": "SQ.XpQn9sZLGv_GU3uiWO7YHq9-_alGjrVX",
    "residueAlphabet": "aa"
  },
  "start": 1040,
  "end": 1089,
  "sequence": null
}

=== vanallenlab/moalmanac-db/dereferenced/sequence_locations/ga4gh_SL.soqw498ekHIRmfkqU2OkjWO5F3jaIWQX.json
{
  "id": "ga4gh:SL.soqw498ekHIRmfkqU2OkjWO5F3jaIWQX",
  "type": "SequenceLocation",
  "name": null,
  "aliases": [],
  "description": "Sequence within refseq:NP_002098.1, the protein product of the MANE Select coding transcript for H3-3A (refseq:NM_002107.7), corresponding to Exon 4.",
  "digest": "soqw498ekHIRmfkqU2OkjWO5F3jaIWQX",
  "sequenceReference": {
    "id": "ga4gh:SQ.2uEiKlgt3rV_axllFiEObLHYBOl2mT38",
    "type": "SequenceReference",
    "name": "NP_002098.1",
    "aliases": [
      "ensembl:ENSP00000254810.3",
      "ga4gh:SQ.2uEiKlgt3rV_axllFiEObLHYBOl2mT38",
      "refseq:NP_002098.1"
    ],
    "description": "The protein product of the MANE Select coding transcript for H3-3A (refseq:NM_002107.7), corresponding to the Refseq protein accession NP_002098.1.",
    "moleculeType": "protein",
    "refgetAccession": "SQ.2uEiKlgt3rV_axllFiEObLHYBOl2mT38",
    "residueAlphabet": "aa"
  },
  "start": 94,
  "end": 136,
  "sequence": null
}

=== vanallenlab/moalmanac-db/dereferenced/sequence_locations/ga4gh_SL.U-rY-staaPS0RvlPe1QYNGut1EEwyRuk.json
{
  "id": "ga4gh:SL.U-rY-staaPS0RvlPe1QYNGut1EEwyRuk",
  "type": "SequenceLocation",
  "name": null,
  "aliases": [],
  "description": "Sequence within refseq:NM_007294.4, the MANE Select coding transcript for BRCA1, corresponding to Exon 11.",
  "digest": "U-rY-staaPS0RvlPe1QYNGut1EEwyRuk",
  "sequenceReference": {
    "id": "ga4gh:SQ.oR9jzdHf6J23TozeyuvTXtwlm6PpUHHl",
    "type": "SequenceReference",
    "name": "NM_007294.4",
    "aliases": [
      "ensembl:ENST00000357654.9",
      "ga4gh:SQ.oR9jzdHf6J23TozeyuvTXtwlm6PpUHHl",
      "refseq:NM_007294.4"
    ],
    "description": "The MANE Select coding transcript for BRCA1, corresponding to the Refseq transcript accession NM_007294.4.",
    "moleculeType": "mRNA",
    "refgetAccession": "SQ.oR9jzdHf6J23TozeyuvTXtwlm6PpUHHl",
    "residueAlphabet": "na"
  },
  "start": 4209,
  "end": 4298,
  "sequence": null
}

=== vanallenlab/moalmanac-db/dereferenced/sequence_locations/ga4gh_SL.dvZQG2wGmOwthzM06C-ySBxeVckRI2NE.json
{
  "id": "ga4gh:SL.dvZQG2wGmOwthzM06C-ySBxeVckRI2NE",
  "type": "SequenceLocation",
  "name": null,
  "aliases": [],
  "description": "Sequence within refseq:NP_004976.2, the protein product of the MANE Select coding transcript for KRAS (refseq:NM_004985.5), corresponding to Exon 5.",
  "digest": "dvZQG2wGmOwthzM06C-ySBxeVckRI2NE",
  "sequenceReference": {
    "id": "ga4gh:SQ.fytWhQSNGnA-86vDiQCxTSzgkk_WfQRS",
    "type": "SequenceReference",
    "name": "NP_004976.2",
    "aliases": [
      "ensembl:ENSP00000308495.3",
      "ga4gh:SQ.fytWhQSNGnA-86vDiQCxTSzgkk_WfQRS",
      "refseq:NP_004976.2"
    ],
    "description": "The protein product of the MANE Select coding transcript for KRAS (refseq:NM_004985.5), corresponding to the Refseq protein accession NP_004976.2.",
    "moleculeType": "protein",
    "refgetAccession": "SQ.fytWhQSNGnA-86vDiQCxTSzgkk_WfQRS",
    "residueAlphabet": "aa"
  },
  "start": 150,
  "end": 188,
  "sequence": null
}

=== vanallenlab/moalmanac-db/dereferenced/sequence_locations/ga4gh_SL.SjoeLK9uKFdQhNbKDDdjDfUy9mWZ4jT7.json
{
  "id": "ga4gh:SL.SjoeLK9uKFdQhNbKDDdjDfUy9mWZ4jT7",
  "type": "SequenceLocation",
  "name": null,
  "aliases": [],
  "description": "Sequence within refseq:NP_001175.2, the protein product of the MANE Select coding transcript for ATR (refseq:NM_001184.4), corresponding to Exon 31. This exon's protein location shares a codon boundary with the adjacent exons on both sides.",
  "digest": "SjoeLK9uKFdQhNbKDDdjDfUy9mWZ4jT7",
  "sequenceReference": {
    "id": "ga4gh:SQ.u5Gzhlhn3KDy6pYiIe9mcVKXFMualGBl",
    "type": "SequenceReference",
    "name": "NP_001175.2",
    "aliases": [
      "ensembl:ENSP00000343741.4",
      "ga4gh:SQ.u5Gzhlhn3KDy6pYiIe9mcVKXFMualGBl",
      "refseq:NP_001175.2"
    ],
    "description": "The protein product of the MANE Select coding transcript for ATR (refseq:NM_001184.4), corresponding to the Refseq protein accession NP_001175.2.",
    "moleculeType": "protein",
    "refgetAccession": "SQ.u5Gzhlhn3KDy6pYiIe9mcVKXFMualGBl",
    "residueAlphabet": "aa"
  },
  "start": 1762,
  "end": 1794,
  "sequence": null
}
