=== vanallenlab/moalmanac-db/schemas/dereferenced/statements.schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "https://moalmanac.org/schemas/dereferenced/statements.schema.json",
  "title": "Statement",
  "description": "A knowledge claim, with contributions, documents, proposition, and strength embedded. `status` and the underlying `indication` are extensions.",
  "type": "object",
  "properties": {
    "id": {
      "type": "string",
      "pattern": "^stmt:(fda|ema|hse|hc|hpra):.+$"
    },
    "type": {
      "const": "Statement"
    },
    "description": {
      "type": "string"
    },
    "contributions": {
      "type": "array",
      "items": {
        "$ref": "contributions.schema.json"
      }
    },
    "reportedIn": {
      "type": "array",
      "items": {
        "$ref": "documents.schema.json"
      }
    },
    "direction": {
      "enum": [
        "supports",
        "disputes",
        "neutral"
      ]
    },
    "proposition": {
      "$ref": "propositions.schema.json"
    },
    "strength": {
      "$ref": "strengths.schema.json"
    },
    "extensions": {
      "type": "array",
      "items": {
        "anyOf": [
          {
            "$ref": "extension.schema.json",
            "properties": {
              "name": {
                "const": "status"
              },
              "value": {
                "enum": [
                  "Active",
                  "Superseded",
                  "Deprecated"
                ]
              }
            }
          },
          {
            "$ref": "extension.schema.json",
            "properties": {
              "name": {
                "const": "indication"
              },
              "value": {
                "$ref": "indications.schema.json",
                "properties": {
                  "extensions": {
                    "not": {
                      "contains": {
                        "type": "object",
                        "properties": {
                          "name": {
                            "const": "statement description"
                          }
                        },
                        "required": [
                          "name"
                        ]
                      }
                    }
                  }
                }
              }
            }
          }
        ]
      },
      "allOf": [
        {
          "contains": {
            "$ref": "extension.schema.json",
            "properties": {
              "name": {
                "const": "status"
              },
              "value": {
                "enum": [
                  "Active",
                  "Superseded",
                  "Deprecated"
                ]
              }
            }
          }
        },
        {
          "contains": {
            "$ref": "extension.schema.json",
            "properties": {
              "name": {
                "const": "indication"
              },
              "value": {
                "$ref": "indications.schema.json",
                "properties": {
                  "extensions": {
                    "not": {
                      "contains": {
                        "type": "object",
                        "properties": {
                          "name": {
                            "const": "statement description"
                          }
                        },
                        "required": [
                          "name"
                        ]
                      }
                    }
                  }
                }
              }
            }
          }
        }
      ]
    }
  },
  "required": [
    "id",
    "type",
    "description",
    "contributions",
    "reportedIn",
    "direction",
    "proposition",
    "strength",
    "extensions"
  ],
  "additionalProperties": false
}

=== vanallenlab/moalmanac-db/dereferenced/statements/stmt_hc_kisqali_1_2.json
{
  "id": "stmt:hc:kisqali:1:2",
  "type": "Statement",
  "description": "Health Canada approved ribociclib, in combination with fulvestrant, for the treatment ostmenopausal women, with HR-positive, HER2-negative advanced or metastatic breast cancer, as initial endocrine-based therapy or following disease progression on endocrine therapy.",
  "contributions": [
    {
      "id": "ctrb:vanallenlab:2024-10-30:0",
      "type": "Contribution",
      "description": "Initial access of FDA approvals",
      "date": "2024-10-30",
      "contributor": {
        "id": "agent:user:vanallenlab",
        "type": "Agent",
        "agentType": "contributor",
        "name": "Van Allen lab",
        "description": "Van Allen lab, Dana-Farber Cancer Institute"
      }
    }
  ],
  "reportedIn": [
    {
      "id": "doc:hc:kisqali",
      "type": "Document",
      "documentType": "Regulatory approval",
      "name": "Kisqali (ribociclib) [product monograph]. HC.",
      "title": null,
      "aliases": [],
      "description": "Novartis Pharmaceuticals Canada Inc. Kisqali (ribociclib) [product monograph]. Health Canada website. https://pdf.hres.ca/dpd_pm/00083872.PDF. Revised March 2026. Accessed April 2026.",
      "urls": [
        "https://pdf.hres.ca/dpd_pm/00083872.PDF",
        "https://health-products.canada.ca/dpd-bdpp/info?lang=eng&code=96295"
      ],
      "doi": null,
      "pmid": null,
      "extensions": [
        {
          "name": "agent",
          "value": {
            "id": "agent:org:hc",
            "type": "Agent",
            "agentType": "organization",
            "name": "Health Canada",
            "description": "Regulatory agency that approves drugs for sale and use in Canada."
          },
          "description": "The organization that published this document."
        },
        {
          "name": "company",
          "value": "Novartis Pharmaceuticals Canada Inc.",
          "description": "The company that manufactures the cancer drug. Only applicable to market authorization documents."
        },
        {
          "name": "drug_name_brand",
          "value": "Kisqali",
          "description": "The brand name of the cancer drug, per this document. Only applicable to market authorization documents."
        },
        {
          "name": "drug_name_generic",
          "value": "ribociclib",
          "description": "The generic name of the cancer drug, per this document. Only applicable to market authorization documents."
        },
        {
          "name": "first_publication_date",
          "value": "2018-03-02",
          "description": "The publication date for the initial version of this document."
        },
        {
          "name": "publication_date",
          "value": "2026-03-26",
          "description": "The publication date for the document."
        },
        {
          "name": "regulatory_identifier",
          "value": null,
          "description": "Identifier assigned by the regulatory agency, such as an FDA application number (e.g. NDA208716, BLA125427) or an EMA product number (e.g. EMEA/H/C/006184)."
        },
        {
          "name": "status",
          "value": "Active",
          "description": "Whether this document is Active or Deprecated within moalmanac-db."
        }
      ]
    }
  ],
  "direction": "supports",
  "proposition": {
    "id": "prop:vtxr:142",
    "type": "VariantTherapeuticResponseProposition",
    "predicate": "predictsSensitivityTo",
    "subjectVariant": {
      "type": "CategoricalVariant",
      "description": "Placeholder. Cat-VRS does not yet support sets of categorical variants. See the 'biomarkers' extension for biomarkers associated with this Proposition."
    },
    "conditionQualifier": {
      "id": "dis:ncit:C9245",
      "conceptType": "Disease",
      "name": "Invasive Breast Carcinoma",
      "mappings": [
        {
          "relation": "exactMatch",
          "coding": {
            "id": "coding:oncotree:BRCA",
            "code": "BRCA",
            "name": "Invasive Breast Carcinoma",
            "system": "https://oncotree.mskcc.org",
            "systemVersion": "oncotree_2025_10_03",
            "iris": [
              "https://oncotree.mskcc.org/?version=oncotree_2025_10_03&field=NAME&search=Invasive+Breast+Carcinoma+%28BRCA%29"
            ]
          }
        }
      ],
      "extensions": [
        {
          "name": "solid_tumor",
          "value": true,
          "description": "Boolean value for if this tumor type is categorized as a solid tumor."
        }
      ],
      "primaryCoding": {
        "id": "coding:ncit:C9245",
        "code": "C9245",
        "name": "Invasive Breast Carcinoma",
        "system": "https://evsexplore.semantics.cancer.gov",
        "systemVersion": "26.08e",
        "iris": [
          "https://evsexplore.semantics.cancer.gov/evsexplore/concept/ncit/C9245"
        ]
      }
    },
    "objectTherapeutic": {
      "id": "txgrp:27",
      "membershipOperator": "AND",
      "therapies": [
        {
          "id": "tx:ncit:C1379",
          "conceptType": "Therapy",
          "name": "Fulvestrant",
          "mappings": [
            {
              "relation": "relatedMatch",
              "coding": {
                "id": "coding:rxcui:282357",
                "code": "282357",
                "name": "fulvestrant",
                "system": "RxNorm",
                "systemVersion": "20250602",
                "iris": [
                  "https://mor.nlm.nih.gov/RxNav/search?searchBy=RXCUI&searchTerm=282357"
                ]
              }
            },
            {
              "relation": "relatedMatch",
              "coding": {
                "id": "coding:omop:1304044",
                "code": "1304044",
                "name": "fulvestrant",
                "system": "OMOP",
                "systemVersion": "v20250827",
                "iris": [
                  "https://athena.ohdsi.org/search-terms/terms/1304044"
                ]
              }
            }
          ],
          "extensions": [
            {
              "name": "therapy_strategy",
              "value": [
                "Estrogen receptor inhibition"
              ],
              "description": "Associated therapeutic strategy or mechanism of action of the therapy."
            },
            {
              "name": "therapy_type",
              "value": "Hormone therapy",
              "description": "Type of cancer treatment from cancer.gov: https://www.cancer.gov/about-cancer/treatment/types"
            }
          ],
          "primaryCoding": {
            "id": "coding:ncit:C1379",
            "code": "C1379",
            "name": "Fulvestrant",
            "system": "https://evsexplore.semantics.cancer.gov",
            "systemVersion": "26.08e",
            "iris": [
              "https://evsexplore.semantics.cancer.gov/evsexplore/concept/ncit/C1379"
            ]
          }
        },
        {
          "id": "tx:ncit:C95701",
          "conceptType": "Therapy",
          "name": "Ribociclib",
          "mappings": [
            {
              "relation": "relatedMatch",
              "coding": {
                "id": "coding:rxcui:1873916",
                "code": "1873916",
                "name": "ribociclib",
                "system": "RxNorm",
                "systemVersion": "02-Mar-2026",
                "iris": [
                  "https://mor.nlm.nih.gov/RxNav/search?searchBy=RXCUI&searchTerm=1873916"
                ]
              }
            },
            {
              "relation": "relatedMatch",
              "coding": {
                "id": "coding:omop:1592911",
                "code": "1592911",
                "name": "ribociclib",
                "system": "OMOP",
                "systemVersion": "v20260227",
                "iris": [
                  "https://athena.ohdsi.org/search-terms/terms/1592911"
                ]
              }
            }
          ],
          "extensions": [
            {
              "name": "therapy_strategy",
              "value": [
                "CDK4/6 inhibition"
              ],
              "description": "Associated therapeutic strategy or mechanism of action of the therapy."
            },
            {
              "name": "therapy_type",
              "value": "Targeted therapy",
              "description": "Type of cancer treatment from cancer.gov: https://www.cancer.gov/about-cancer/treatment/types"
            }
          ],
          "primaryCoding": {
            "id": "coding:ncit:C95701",
            "code": "C95701",
            "name": "Ribociclib",
            "system": "https://evsexplore.semantics.cancer.gov",
            "systemVersion": "26.08e",
            "iris": [
              "https://evsexplore.semantics.cancer.gov/evsexplore/concept/ncit/C95701"
            ]
          }
        }
      ]
    },
    "extensions": [
      {
        "name": "biomarkers",
        "value": [
          {
            "id": "bmkr.criterion:1",
            "present": true,
            "subject": {
              "id": "bmkr:1",
              "type": "CategoricalVariant",
              "name": "ER positive",
              "constraints": [],
              "extensions": [
                {
                  "name": "biomarker_type",
                  "value": "Protein expression"
                },
                {
                  "name": "marker",
                  "value": "Estrogen receptor (ER)"
                },
                {
                  "name": "unit",
                  "value": "status"
                },
                {
                  "name": "equality",
                  "value": "="
                },
                {
                  "name": "value",
                  "value": "Positive"
                }
              ]
            }
          },
          {
            "id": "bmkr.criterion:2",
            "present": true,
            "subject": {
